const postalData = {
    1: { districtNo: 1, districtName: 'Raffles Place, Cecil, Marina, People\'s Park' },
    2: { districtNo: 1, districtName: 'Raffles Place, Cecil, Marina, People\'s Park' },
    3: { districtNo: 1, districtName: 'Raffles Place, Cecil, Marina, People\'s Park' },
    4: { districtNo: 1, districtName: 'Raffles Place, Cecil, Marina, People\'s Park' },
    5: { districtNo: 1, districtName: 'Raffles Place, Cecil, Marina, People\'s Park' },
    6: { districtNo: 1, districtName: 'Raffles Place, Cecil, Marina, People\'s Park' },
    7: { districtNo: 2, districtName: 'Anson, Tanjong Pagar' },
    8: { districtNo: 2, districtName: 'Anson, Tanjong Pagar' },
    9: { districtNo: 4, districtName: 'Telok Blangah, Harbourfront' },
    10: { districtNo: 4, districtName: 'Telok Blangah, Harbourfront' },
    11: { districtNo: 5, districtName: 'Pasir Panjang, Hong Leong Garden, Clementi New Town' },
    12: { districtNo: 5, districtName: 'Pasir Panjang, Hong Leong Garden, Clementi New Town' },
    13: { districtNo: 5, districtName: 'Pasir Panjang, Hong Leong Garden, Clementi New Town' },
    14: { districtNo: 3, districtName: 'Queenstown, Tiong Bahru' },
    15: { districtNo: 3, districtName: 'Queenstown, Tiong Bahru' },
    16: { districtNo: 3, districtName: 'Queenstown, Tiong Bahru' },
    17: { districtNo: 6, districtName: 'High Street, Beach Road (part)' },
    18: { districtNo: 7, districtName: 'Middle Road, Golden Mile' },
    19: { districtNo: 7, districtName: 'Middle Road, Golden Mile' },
    20: { districtNo: 8, districtName: 'Little India' },
    21: { districtNo: 8, districtName: 'Little India' },
    22: { districtNo: 9, districtName: 'Orchard, Cairnhill, River Valley' },
    23: { districtNo: 9, districtName: 'Orchard, Cairnhill, River Valley' },
    24: { districtNo: 10, districtName: 'Ardmore, Bukit Timah, Holland Road, Tanglin' },
    25: { districtNo: 10, districtName: 'Ardmore, Bukit Timah, Holland Road, Tanglin' },
    26: { districtNo: 10, districtName: 'Ardmore, Bukit Timah, Holland Road, Tanglin' },
    27: { districtNo: 10, districtName: 'Ardmore, Bukit Timah, Holland Road, Tanglin' },
    28: { districtNo: 11, districtName: 'Watten Estate, Novena, Thomson' },
    29: { districtNo: 11, districtName: 'Watten Estate, Novena, Thomson' },
    30: { districtNo: 11, districtName: 'Watten Estate, Novena, Thomson' },
    31: { districtNo: 12, districtName: 'Balestier, Toa Payoh, Serangoon' },
    32: { districtNo: 12, districtName: 'Balestier, Toa Payoh, Serangoon' },
    33: { districtNo: 12, districtName: 'Balestier, Toa Payoh, Serangoon' },
    34: { districtNo: 13, districtName: 'Macpherson, Braddell' },
    35: { districtNo: 13, districtName: 'Macpherson, Braddell' },
    36: { districtNo: 13, districtName: 'Macpherson, Braddell' },
    37: { districtNo: 13, districtName: 'Macpherson, Braddell' },
    38: { districtNo: 14, districtName: 'Geylang, Eunos' },
    39: { districtNo: 14, districtName: 'Geylang, Eunos' },
    40: { districtNo: 14, districtName: 'Geylang, Eunos' },
    41: { districtNo: 14, districtName: 'Geylang, Eunos' },
    42: { districtNo: 15, districtName: 'Katong, Joo Chiat, Amber Road' },
    43: { districtNo: 15, districtName: 'Katong, Joo Chiat, Amber Road' },
    44: { districtNo: 15, districtName: 'Katong, Joo Chiat, Amber Road' },
    45: { districtNo: 15, districtName: 'Katong, Joo Chiat, Amber Road' },
    46: { districtNo: 16, districtName: 'Bedok, Upper East Coast, Eastwood, Kew Drive' },
    47: { districtNo: 16, districtName: 'Bedok, Upper East Coast, Eastwood, Kew Drive' },
    48: { districtNo: 16, districtName: 'Bedok, Upper East Coast, Eastwood, Kew Drive' },
    49: { districtNo: 17, districtName: 'Loyang, Changi' },
    50: { districtNo: 17, districtName: 'Loyang, Changi' },
    51: { districtNo: 18, districtName: 'Tampines, Pasir Ris' },
    52: { districtNo: 18, districtName: 'Tampines, Pasir Ris' },
    53: { districtNo: 19, districtName: 'Serangoon Garden, Hougang, Punggol' },
    54: { districtNo: 19, districtName: 'Serangoon Garden, Hougang, Punggol' },
    55: { districtNo: 19, districtName: 'Serangoon Garden, Hougang, Punggol' },
    56: { districtNo: 20, districtName: 'Bishan, Ang Mo Kio' },
    57: { districtNo: 20, districtName: 'Bishan, Ang Mo Kio' },
    58: { districtNo: 21, districtName: 'Upper Bukit Timah, Clementi Park, Ulu Pandan' },
    59: { districtNo: 21, districtName: 'Upper Bukit Timah, Clementi Park, Ulu Pandan' },
    60: { districtNo: 22, districtName: 'Jurong' },
    61: { districtNo: 22, districtName: 'Jurong' },
    62: { districtNo: 22, districtName: 'Jurong' },
    63: { districtNo: 22, districtName: 'Jurong' },
    64: { districtNo: 22, districtName: 'Jurong' },
    65: { districtNo: 23, districtName: 'Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang' },
    66: { districtNo: 23, districtName: 'Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang' },
    67: { districtNo: 23, districtName: 'Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang' },
    68: { districtNo: 23, districtName: 'Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang' },
    69: { districtNo: 24, districtName: 'Lim Chu Kang, Tengah' },
    70: { districtNo: 24, districtName: 'Lim Chu Kang, Tengah' },
    71: { districtNo: 24, districtName: 'Lim Chu Kang, Tengah' },
    72: { districtNo: 25, districtName: 'Kranji, Woodgrove' },
    73: { districtNo: 25, districtName: 'Kranji, Woodgrove' },
    75: { districtNo: 27, districtName: 'Yishun, Sembawang' },
    76: { districtNo: 27, districtName: 'Yishun, Sembawang' },
    77: { districtNo: 26, districtName: 'Upper Thomson, Springleaf' },
    78: { districtNo: 26, districtName: 'Upper Thomson, Springleaf' },
    79: { districtNo: 28, districtName: 'Seletar' },
    80: { districtNo: 28, districtName: 'Seletar' },
    81: { districtNo: 17, districtName: 'Loyang, Changi' },
    82: { districtNo: 19, districtName: 'Serangoon Garden, Hougang, Punggol' }
  };

  const NumbertoName = { 
    1: 'Raffles Place, Cecil, Marina, People\'s Park',
    2: 'Anson, Tanjong Pagar',
    3: 'Queenstown, Tiong Bahru',
    4: 'Telok Blangah, Harbourfront',
    5: 'Pasir Panjang, Hong Leong Garden, Clementi New Town',
    6: 'High Street, Beach Road (part)',
    7: 'Middle Road, Golden Mile',
    8: 'Little India',
    9: 'Orchard, Cairnhill, River Valley',
    10: 'Ardmore, Bukit Timah, Holland Road, Tanglin',
    11: 'Watten Estate, Novena, Thomson',
    12: 'Balestier, Toa Payoh, Serangoon',
    13: 'Macpherson, Braddell',
    14: 'Geylang, Eunos',
    15: 'Katong, Joo Chiat, Amber Road',
    16: 'Bedok, Upper East Coast, Eastwood, Kew Drive',
    17: 'Loyang, Changi',
    18: 'Tampines, Pasir Ris',
    19: 'Serangoon Garden, Hougang, Punggol',
    20: 'Bishan, Ang Mo Kio',
    21: 'Upper Bukit Timah, Clementi Park, Ulu Pandan',
    22: 'Jurong',
    23: 'Hillview, Dairy Farm, Bukit Panjang, Choa Chu Kang',
    24: 'Lim Chu Kang, Tengah',
    25: 'Kranji, Woodgrove',
    26: 'Upper Thomson, Springleaf',
    27: 'Yishun, Sembawang',
    28: 'Seletar'  
  };

  module.exports = {postalData, NumbertoName};